<?php defined('_ENGINE') or die('Access Denied'); return array (
  0 => 'Activity',
  1 => 'Album',
  2 => 'Announcement',
  3 => 'Authorization',
  4 => 'Blog',
  5 => 'Chat',
  6 => 'Classified',
  7 => 'Core',
  8 => 'Event',
  9 => 'Fields',
  10 => 'Forum',
  11 => 'Group',
  12 => 'Invite',
  13 => 'Messages',
  14 => 'Mobi',
  15 => 'Music',
  16 => 'Network',
  17 => 'Payment',
  18 => 'Poll',
  19 => 'Storage',
  20 => 'User',
  21 => 'Video',
); ?>